Repository AltraMayor/gatekeeper, pull requests merged in 2021-05, with the labels that each got.

#475 Change user and drop capabilities
  .github/workflows/c-cpp.yml
  Makefile
  README.md
  config/dynamic.c
  cps/main.c
  ggu/main.c
  gk/main.c
  gt/main.c
  include/gatekeeper_net.h
  lib/launch.c
  lib/net.c
  lls/main.c
  main/main.c
  sol/main.c
Labels: bug

#482 Review the initialization of the KNI interfaces
  cps/main.c
Labels: enhancement

#479 Improve log entries for production
  cps/kni.c
  lib/l2.c
Labels: Operational demand

#483 cps: disable promiscuous mode on KNI interfaces
  cps/kni.c
  cps/kni.h
  cps/main.c
Labels: enhancement
