Repository AltraMayor/gatekeeper, pull requests merged in 2021-07, with the labels that each got.

#501 cps: request capability CAP_SYS_MODULE
  cps/main.c
Labels: enhancement

#503 Add gcc-multilib build dependency (#499)
  README.md
  debian/control
Labels: enhancement

#504 gt: correct NUMA node of LPM tables
  gt/lua_lpm.c
  gt/main.c
  include/gatekeeper_gt.h
Labels: enhancement

#500 gt: allow policies to request more hugepages after boot
  config/dynamic.c
  gkctl/scripts/reload_policy.lua
  gt/main.c
Labels: Operational demand

#505 lua/dylib: return value from update_gt_lua_states_incrementally
  lua/gatekeeper/dylib.lua
Labels: bug

#506 Review Lua lpmlib
  gt/lua_lpm.c
  lua/examples/policy.lua
Labels: Production requirement, bug, enhancement

#511 cps: push not-handled ICMP packets to KNI interfaces
  include/gatekeeper_lls.h
  lls/cache.c
Labels: Production requirement

#513 acl: run extension functions only once per packet
  lib/acl.c
Labels: enhancement

#514 cps: forward all TCP packets the KNI interfaces
  cps/main.c
  include/gatekeeper_cps.h
  lua/cps.lua
  lua/gatekeeper/staticlib.lua
Labels: Operational demand

#515 acl: combine ACL types
  lib/acl.c
Labels: enhancement
