Repository AltraMayor/gatekeeper, pull requests merged in 2024-01, with the labels that each got.

#664 Add hopscotch hashing
  Makefile
  gk/main.c
  include/gatekeeper_gk.h
  include/gatekeeper_hash.h
  lib/hash.c
  lua/gatekeeper/staticlib.lua
  lua/gk.lua
Labels: enhancement, Production requirement

#667 gatekeeper: add pkg-config as package dependency
  .github/workflows/c-cpp.yml
  README.md
Labels: Operational demand

#669 lib/hash: avoid mixing bucket and user indexes
  gk/main.c
  include/gatekeeper_hash.h
  lib/hash.c
Labels: bug

#670 gk: drop packets of flows not backed by a flow entry
  gk/main.c
Labels: enhancement

#671 gk: handle hs_hash_add_key_with_hash() == -EEXIST
  gk/main.c
Labels: enhancement
